# Generated by Django 5.2.5 on 2025-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='what_to_wear',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='cities.city'),
        ),
    ]
