# Generated by Django 5.2.5 on 2025-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_description_city_updated_at_city_what_to_wear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hash_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
