# Generated by Django 5.2.5 on 2025-08-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_city_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
